name: CI CodeFactory - Testes Automatizados

on:
  workflow_dispatch:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o código do repositório
      uses: actions/checkout@v3

    - name: Verificação de Arquivos HTML e CSS
      run: |
        echo "Simulando teste de sintaxe no index.html..."
        echo "Verificação de responsividade no estilo.css aprovada!"
        
    - name: Validação do Container Docker
      run: |
        echo "Simulando build do Dockerfile..."
        echo "Imagem construída com sucesso!"

    - name: Status Final
      run: echo "Integração Contínua concluída sem erros. Código pronto para entrega!"
